package com.neo4j.sync.engine;

public enum ChangeType {
    ADD_NODE, DELETE_NODE, ADD_RELATION, DELETE_RELATION, ADD_PROPERTY, NODE_PROPERTY_CHANGE, ADD_RELATION_PROPERTY, RELATION_PROPERTY_CHANGE
}
